apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passion-cuisine
  name: angular-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: passion-cuisine
      component: angular
  template:
    metadata:
      labels:
        app: passion-cuisine
        component: angular
    spec:
      containers:
      - image: passioncuisine/frontend
        name: angular
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
