apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-admin
  name: postgres-admin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-admin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        image: dpage/pgadmin4
        name: postgres-admin
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: postgres-admin-claim0
        - mountPath: /root/.pgadmin
          name: postgres-admin
      restartPolicy: Always
      volumes:
      - name: postgres-admin-claim0
        persistentVolumeClaim:
          claimName: postgres-admin-claim0
      - name: postgres-admin
        persistentVolumeClaim:
          claimName: postgres-admin
status: {}
