apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passion-cuisine
  name: postgres-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: passion-cuisine
      component: postgres
  template:
    metadata:
      labels:
        app: passion-cuisine
        component: postgres
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_DB
          value: passion-cuisine
        - name: POSTGRES_PASSWORD
          value: pi-group-6
        - name: POSTGRES_USER
          value: pi-group-6
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /docker-entrypoint-initdb.d/data.sql
        - name: npa-city
          mountPath: /docker-entrypoint-initdb.d/npa_city.sql
        - name: procedures
          mountPath: /docker-entrypoint-initdb.d/procedures.sql
        - name: schema
          mountPath: /docker-entrypoint-initdb.d/schema.sql
        - name: spring-role
          mountPath: /docker-entrypoint-initdb.d/spring_role.sql
        - name: triggers
          mountPath: /docker-entrypoint-initdb.d/triggers.sql
      restartPolicy: Always
      volumes:
        - name: data
          configMap:
            name: data.sql
        - name: npa-city
          configMap:
            name: npa-city.sql
        - name: procedures
          configMap:
            name: procedures.sql
        - name: schema
          configMap:
            name: schema.sql
        - name: spring-role
          configMap:
            name: spring-role.sql
        - name: triggers
          configMap:
            name: triggers.sql
