apiVersion: v1
kind: Service
metadata:
  labels:
    component: spring-boot
  name: spring-boot-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: passion-cuisine
    component: spring-boot
  type: LoadBalancer
