apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot
  name: spring-boot
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-boot
    spec:
      containers:
      - env:
        - name: PASSION_CUISINE_DB_HOST
          value: postgres:5432
        - name: PASSION_CUISINE_DB_NAME
          value: passion-cuisine
        - name: PASSION_CUISINE_DB_PASS
          value: spring-user-pass
        - name: PASSION_CUISINE_DB_USER
          value: spring-user
        image: spring-boot
        name: spring-boot
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
