apiVersion: v1
kind: Service
metadata:
  labels:
    component: angular
  name: angular-svc
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: passion-cuisine
    component: angular
  type: LoadBalancer
