apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passion-cuisine
  name: postgres-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passion-cuisine
      component: postgres-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: passion-cuisine
        component: postgres-admin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        image: dpage/pgadmin4
        name: postgres-admin
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: postgres-admin-claim0
        - mountPath: /root/.pgadmin
          name: postgres-admin
      restartPolicy: Always
      volumes:
      - name: postgres-admin-claim0
        persistentVolumeClaim:
          claimName: postgres-admin-claim0
      - name: postgres-admin
        persistentVolumeClaim:
          claimName: postgres-admin
status: {}
