apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgres-admin
  name: postgres-admin-svc
spec:
  ports:
  - name: "5480"
    port: 5480
    targetPort: 80
  selector:
    app: passion-cuisine
    component: postgres-admin
  type: ClusterIP
