apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passion-cuisine
  name: postgres-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: passion-cuisine
      component: postgres
  template:
    metadata:
      labels:
        app: passion-cuisine
        component: postgres
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_DB
          value: passion-cuisine
        - name: POSTGRES_PASSWORD
          value: pi-group-6
        - name: POSTGRES_USER
          value: pi-group-6
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: scripts
          mountPath: /docker-entrypoint-initdb.d/
      restartPolicy: Always
      volumes:
        - name: scripts
          configMap:
            name: scripts
