apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgres
  name: postgres-svc
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: passion-cuisine
    component: postgres
  clusterIP: 10.100.72.37
